maven_layout()

jar_library(name='route-finagle-http',
  dependencies=[
    'webbing/route-finagle-http/src/main/scala'
  ]
)

jar_library(name='tests',
  dependencies=[
    'webbing/route-finagle-http/src/test/scala'
  ]
)
