maven_layout()

jar_library(name='route-finagle-http',
  dependencies=[
    pants('webbing/route-finagle-http/src/main/scala')
  ]
)

jar_library(name='tests',
  dependencies=[
    pants('webbing/route-finagle-http/src/test/scala')
  ]
)
