maven_layout()

target(name='route-finagle-http',
  dependencies=[
    'webbing/route-finagle-http/src/main/scala'
  ]
)

target(name='tests',
  dependencies=[
    'webbing/route-finagle-http/src/test/scala'
  ]
)
